spring:
  profiles:
    active: test
  datasource:
    # 配置数据源类型
    type:
      com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/myphoto?useUnicode=true&characterEncoding=UTF-8
    username: postgres
    password: postgres
    # 初始化，最小，最大连接数
    initialSize: 3
    minidle: 3
    maxActive: 18
    # 获取数据库连接等待的超时时间
    maxWait: 60000
    # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM dual
    # 配置监控统计拦截的filters,去掉后，监控界面的sql无法统计
    filters: stat,wall,log4j


  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.oldpei.myback.model

---
spring:
  profiles: test

oldpei:
  filepath: C:\Users\jixing.pei\Desktop\img\
  expiretime: 36000000
  tokensecret: oldpeisecret
  domain: "http://10.143.3.122:9999/"
server:
  port: 9999


---
spring:
  profiles: dev
oldpei:
  filepath:
  expiretime: 36000000
  tokensecret: oldpeisecret
  domain: ""
server:
  port: 9999


---
spring:
  profiles: prod
oldpei:
  filepath: /opt/myphoto/photo/
  expiretime: 36000000
  tokensecret: oldpeisecret
  domain: "http://oldpei.icu/web/img/"
server:
  port: 9999


  #spring:
  #  profiles:
  #    active: aeolian
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/personInfo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  #    username: root
  #    password: 1234
  #    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis:
#  mapper-locations: mapper/*.xml
#  type-aliases-package: com.oldpei.personinfo.model
#  configuration:
#    map-underscore-to-camel-case: true
#
#
#redis:
#  host: localhost
#  port: 6379
#  max-wait: 30000
#  max-active: 100
#  max-idle: 20
#  min-dile: 0
#  timeout: 3000
