CREATE SCHEMA MYPHOTO;

CREATE TABLE MYPHOTO.T_PHOTO(
  UNIQUE_ID SERIAL NOT NULL
  , DATE VARCHAR (8) NOT NULL
  , TYPE VARCHAR
  , NAME VARCHAR
  , PATH VARCHAR
  , ACTIVE_FLG CHARACTER (1) NOT NULL
  , SYS_INSERT_ID VARCHAR (30)
  , SYS_INSERT_DATE TIMESTAMP WITHOUT TIME ZONE
  , SYS_UPDATE_ID VARCHAR (30)
  , SYS_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE
);

ALTER TABLE MYPHOTO.T_PHOTO ADD CONSTRAINT T_PHOTO_PK PRIMARY KEY (UNIQUE_ID);