CREATE SCHEMA MYPHOTO;

CREATE TABLE MYPHOTO.T_PHOTO(
  UNIQUE_ID SERIAL NOT NULL
  , DATE VARCHAR (8) NOT NULL
  , TYPE VARCHAR
  , NAME VARCHAR
  , PATH VARCHAR
  , STORAGE  VARCHAR
  , ACTIVE_FLG CHARACTER (1) NOT NULL
  , SYS_INSERT_ID VARCHAR (30)
  , SYS_INSERT_DATE TIMESTAMP WITHOUT TIME ZONE
  , SYS_UPDATE_ID VARCHAR (30)
  , SYS_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE
);

ALTER TABLE MYPHOTO.T_PHOTO ADD CONSTRAINT T_PHOTO_PK PRIMARY KEY (UNIQUE_ID);
CREATE  INDEX T_PHOTO_NO_DATE ON MYPHOTO.T_PHOTO (DATE);

CREATE TABLE MYPHOTO.T_PHOTOTYPE(
  UNIQUE_ID SERIAL NOT NULL
  , TYPE VARCHAR
  , ACTIVE_FLG CHARACTER (1) NOT NULL
  , SYS_INSERT_ID VARCHAR (30)
  , SYS_INSERT_DATE TIMESTAMP WITHOUT TIME ZONE
  , SYS_UPDATE_ID VARCHAR (30)
  , SYS_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE
);
ALTER TABLE MYPHOTO.T_PHOTOTYPE ADD CONSTRAINT T_PHOTOTYPE_PK PRIMARY KEY (UNIQUE_ID);
CREATE  INDEX T_PHOTOTYPE_NO_TYPE ON MYPHOTO.T_PHOTOTYPE (TYPE);

