# yaml 配置实例
version: '0.0.1'
services:
  myfront:
    build:
      context: ./
      dockerfile: Dockerfile_front
    ports:
    - "80:9528"
    volumes:
    - /opt/myphoto/myfront:/opt/myphoto/myfront
    - /opt/myphoto/nginx/config/nginx.conf:/etc/nginx/nginx.conf
    image: myfront:0.0.1
  myback:
    image: myback:0.0.1
    build:
      context: ./
      dockerfile: Dockerfile_back
      ports:
        - "9999:9999"
      volumes:
        - /opt/myphoto/photo/:/opt/myphoto/photo/
