DROP TABLE SD.SD_USER_ROLE;
CREATE TABLE SD.SD_USER_ROLE (
UNIQUE_ID	SERIAL		NOT NULL	,
USER_ID	VARCHAR(30)		NOT NULL	,
ROLE_CODE	VARCHAR(50)		NOT NULL	,
ACTIVE_FLG	CHAR(1)	DEFAULT '1'	NOT NULL	,
SYS_INSERT_ID	VARCHAR(30)			,
SYS_INSERT_DATE	TIMESTAMP WITHOUT TIME ZONE			,
SYS_UPDATE_ID	VARCHAR(30)			,
SYS_UPDATE_DATE	TIMESTAMP WITHOUT TIME ZONE			);
				
				
				
ALTER TABLE SD.SD_USER_ROLE ADD CONSTRAINT SD_UR_PK PRIMARY KEY (UNIQUE_ID);				
