CREATE TABLE SD.SD_USER (				
UNIQUE_ID	SERIAL		NOT NULL	,
USER_ID	VARCHAR(30)		NOT NULL	,
USER_NAME	VARCHAR(50)			,
PASSWORD	VARCHAR(100)		NOT NULL	,
USE_LDAP	CHAR(1)	DEFAULT '0'	NOT NULL	,
PRE_PWD_CHG_DATE	TIMESTAMP WITHOUT TIME ZONE		NOT NULL	,
LOCK_FLG	CHAR(1)	DEFAULT '0'	NOT NULL	,
PWD_FAILED_COUNT	INTEGER	DEFAULT 0	NOT NULL	,
ACTIVE_FLG	CHAR(1)	DEFAULT '1'	NOT NULL	,
SYS_INSERT_ID	VARCHAR(30)			,
SYS_INSERT_DATE	TIMESTAMP WITHOUT TIME ZONE			,
SYS_UPDATE_ID	VARCHAR(30)			,
SYS_UPDATE_DATE	TIMESTAMP WITHOUT TIME ZONE			);
				
				
				
ALTER TABLE SD.SD_USER ADD CONSTRAINT SD_USER_PK PRIMARY KEY (UNIQUE_ID);				
CREATE  INDEX SD_INDEX_USERID ON SD.SD_USER (USER_ID);				
