DROP TABLE SD.SD_MENU_ROLE;
CREATE TABLE SD.SD_MENU_ROLE (
UNIQUE_ID	SERIAL		NOT NULL	,
MENU_ID	VARCHAR(30)		NOT NULL	,
ROLE_CODE	VARCHAR(50)		NOT NULL	,
ACTIVE_FLG	CHAR(1)	DEFAULT '1'	NOT NULL	,
SYS_INSERT_ID	VARCHAR(30)			,
SYS_INSERT_DATE	TIMESTAMP WITHOUT TIME ZONE			,
SYS_UPDATE_ID	VARCHAR(30)			,
SYS_UPDATE_DATE	TIMESTAMP WITHOUT TIME ZONE			);
				
				
				
ALTER TABLE SD.SD_MENU_ROLE ADD CONSTRAINT SD_MR_PK PRIMARY KEY (UNIQUE_ID);				
